import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// src/components/Cita.tsx
import { useState } from "react";
export default function Cita() {
    const [enviado, setEnviado] = useState(false);
    const handleSubmit = (e) => {
        e.preventDefault();
        setEnviado(true);
        setTimeout(() => setEnviado(false), 4000);
    };
    return (_jsxs("section", { id: "cita", className: "bg-white py-16 px-4 font-default", children: [_jsxs("div", { className: "max-w-3xl mx-auto text-center mb-10", children: [_jsx("h2", { className: "text-3xl font-bold text-[#1977cc] mb-4 font-heading", children: "Solicitar una Cita" }), _jsx("p", { className: "text-gray-600", children: "Complete el siguiente formulario para reservar una cita con uno de nuestros especialistas." })] }), _jsxs("form", { onSubmit: handleSubmit, className: "max-w-4xl mx-auto bg-gray-50 p-8 rounded-lg shadow-lg grid gap-6", children: [_jsxs("div", { className: "grid md:grid-cols-3 gap-4", children: [_jsx("input", { type: "text", placeholder: "Nombre completo", className: "form-input", required: true }), _jsx("input", { type: "email", placeholder: "Correo electr\u00F3nico", className: "form-input", required: true }), _jsx("input", { type: "tel", placeholder: "Tel\u00E9fono", className: "form-input", required: true })] }), _jsxs("div", { className: "grid md:grid-cols-3 gap-4", children: [_jsx("input", { type: "datetime-local", className: "form-input", required: true }), _jsxs("select", { className: "form-input", required: true, children: [_jsx("option", { value: "", children: "Seleccione Departamento" }), _jsx("option", { value: "cardiologia", children: "Cardiolog\u00EDa" }), _jsx("option", { value: "neurologia", children: "Neurolog\u00EDa" }), _jsx("option", { value: "pediatria", children: "Pediatr\u00EDa" })] }), _jsxs("select", { className: "form-input", required: true, children: [_jsx("option", { value: "", children: "Seleccione M\u00E9dico" }), _jsx("option", { value: "dr1", children: "Dr. Luis P\u00E9rez" }), _jsx("option", { value: "dr2", children: "Dra. Ana L\u00F3pez" }), _jsx("option", { value: "dr3", children: "Dr. Mario Garc\u00EDa" })] })] }), _jsx("textarea", { rows: 4, placeholder: "Mensaje adicional (opcional)", className: "form-input" }), _jsx("div", { className: "text-center", children: _jsx("button", { type: "submit", className: "bg-[#1977cc] text-white px-8 py-3 rounded-full hover:bg-[#166ab5] transition font-medium", children: "Reservar Cita" }) }), enviado && (_jsx("p", { className: "text-green-600 text-center font-semibold animate-fade-in", children: "\u2705 Tu cita fue registrada correctamente." }))] })] }));
}
