import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// src/components/Contacto.tsx
import { FaMapMarkerAlt, FaPhoneAlt, FaEnvelope, } from "react-icons/fa";
export default function Contacto() {
    return (_jsx("section", { id: "contacto", className: "bg-white py-16 px-4", children: _jsxs("div", { className: "max-w-7xl mx-auto font-default", children: [_jsx("h2", { className: "text-3xl font-bold text-[#1977cc] text-center mb-4 font-heading", children: "Cont\u00E1ctanos" }), _jsx("p", { className: "text-center text-gray-600 mb-10", children: "\u00BFTienes dudas? \u00BFDeseas una atenci\u00F3n especializada? Env\u00EDanos un mensaje o vis\u00EDtanos." }), _jsx("div", { className: "mb-10", children: _jsx("iframe", { className: "w-full h-72 rounded-md shadow", src: "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d48389.78314118045!2d-74.006138!3d40.710059!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c25a22a3bda30d%3A0xb89d1fe6bc499443!2sDowntown%20Conference%20Center!5e0!3m2!1sen!2sus!4v1676961268712!5m2!1sen!2sus", allowFullScreen: true, loading: "lazy", referrerPolicy: "no-referrer-when-downgrade" }) }), _jsxs("div", { className: "grid lg:grid-cols-2 gap-10", children: [_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "flex items-start gap-4", children: [_jsx(FaMapMarkerAlt, { className: "text-2xl text-[#1977cc] mt-1" }), _jsxs("div", { children: [_jsx("h4", { className: "font-semibold text-gray-800", children: "Direcci\u00F3n" }), _jsx("p", { className: "text-gray-600", children: "Calle Bol\u00EDvar #123, Sucre, Bolivia" })] })] }), _jsxs("div", { className: "flex items-start gap-4", children: [_jsx(FaPhoneAlt, { className: "text-2xl text-[#1977cc] mt-1" }), _jsxs("div", { children: [_jsx("h4", { className: "font-semibold text-gray-800", children: "Tel\u00E9fono" }), _jsx("p", { className: "text-gray-600", children: "(04) 645-1234" })] })] }), _jsxs("div", { className: "flex items-start gap-4", children: [_jsx(FaEnvelope, { className: "text-2xl text-[#1977cc] mt-1" }), _jsxs("div", { children: [_jsx("h4", { className: "font-semibold text-gray-800", children: "Email" }), _jsx("p", { className: "text-gray-600", children: "info@hospitalsantabarbara.org" })] })] })] }), _jsxs("form", { onSubmit: (e) => {
                                e.preventDefault();
                                alert("✅ Mensaje enviado correctamente.");
                            }, className: "grid gap-4 bg-gray-50 p-6 rounded-lg shadow-lg", children: [_jsx("input", { type: "text", placeholder: "Nombre completo", className: "form-input", required: true }), _jsx("input", { type: "email", placeholder: "Correo electr\u00F3nico", className: "form-input", required: true }), _jsx("input", { type: "text", placeholder: "Asunto", className: "form-input", required: true }), _jsx("textarea", { rows: 4, placeholder: "Mensaje", className: "form-input", required: true }), _jsx("button", { type: "submit", className: "bg-[#1977cc] text-white py-3 rounded-md hover:bg-[#166ab5] transition text-sm font-medium", children: "Enviar mensaje" })] })] })] }) }));
}
