import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect } from "react";
import AOS from "aos";
import "aos/dist/aos.css";
import { FaClipboardList, FaGem, FaFlask } from "react-icons/fa";
export default function Hero() {
    useEffect(() => {
        AOS.init({ once: true, duration: 1000 });
    }, []);
    return (_jsx("section", { id: "inicio", className: "relative bg-[url('/assets/img/hero-bg.jpg')] bg-cover bg-center bg-no-repeat py-20 px-4", children: _jsxs("div", { className: "max-w-7xl mx-auto w-full grid lg:grid-cols-2 gap-12 items-center", children: [_jsxs("div", { className: "space-y-8", "data-aos": "fade-up", children: [_jsxs("h1", { className: "text-4xl md:text-5xl font-extrabold text-gray-800 leading-tight font-heading", children: ["Hospital ", _jsx("span", { className: "text-[#1977cc]", children: "Santa B\u00E1rbara" })] }), _jsx("p", { className: "text-lg text-gray-600", children: "Somos un equipo de profesionales comprometidos con tu salud. Nuestra misi\u00F3n es brindar atenci\u00F3n m\u00E9dica humana y de calidad." }), _jsxs("div", { className: "bg-[#1977cc] text-white rounded-lg p-6 shadow-md max-w-xl", children: [_jsx("h3", { className: "text-2xl font-bold mb-3", children: "\u00BFPor qu\u00E9 elegirnos?" }), _jsx("p", { className: "text-sm leading-relaxed mb-4", children: "Brindamos atenci\u00F3n oportuna, c\u00E1lida y especializada. Nuestro hospital cuenta con tecnolog\u00EDa de vanguardia y personal m\u00E9dico altamente calificado para garantizar tu bienestar." }), _jsx("a", { href: "#nosotros", className: "inline-block text-sm bg-white text-[#1977cc] px-4 py-2 rounded-full font-semibold hover:bg-gray-100 transition", children: "Con\u00F3cenos \u2192" })] })] }), _jsxs("div", { className: "grid gap-6 md:grid-cols-1 lg:grid-cols-3", "data-aos": "fade-left", children: [_jsxs("div", { className: "bg-white bg-opacity-80 backdrop-blur-sm p-6 rounded-lg shadow text-center", children: [_jsx(FaClipboardList, { className: "text-[#1977cc] text-3xl mx-auto mb-3" }), _jsx("h4", { className: "text-lg font-bold text-gray-800 mb-2", children: "Atenci\u00F3n integral" }), _jsx("p", { className: "text-sm text-gray-600", children: "Diagn\u00F3stico, prevenci\u00F3n y tratamiento desde la primera consulta." })] }), _jsxs("div", { className: "bg-white bg-opacity-80 backdrop-blur-sm p-6 rounded-lg shadow text-center", children: [_jsx(FaGem, { className: "text-[#1977cc] text-3xl mx-auto mb-3" }), _jsx("h4", { className: "text-lg font-bold text-gray-800 mb-2", children: "Profesionales de calidad" }), _jsx("p", { className: "text-sm text-gray-600", children: "Nuestro equipo m\u00E9dico est\u00E1 conformado por especialistas certificados." })] }), _jsxs("div", { className: "bg-white bg-opacity-80 backdrop-blur-sm p-6 rounded-lg shadow text-center", children: [_jsx(FaFlask, { className: "text-[#1977cc] text-3xl mx-auto mb-3" }), _jsx("h4", { className: "text-lg font-bold text-gray-800 mb-2", children: "Infraestructura moderna" }), _jsx("p", { className: "text-sm text-gray-600", children: "Ambientes equipados para una atenci\u00F3n segura y eficaz." })] })] })] }) }));
}
