import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect } from "react";
import AOS from "aos";
import "aos/dist/aos.css";
import { FaVial, FaPumpMedical, FaHeart } from "react-icons/fa6";
export default function Nosotros() {
    useEffect(() => {
        AOS.init({ once: true, duration: 1000 });
    }, []);
    return (_jsx("section", { id: "nosotros", className: "bg-white py-16 px-4 font-default", children: _jsxs("div", { className: "max-w-7xl mx-auto grid md:grid-cols-2 gap-10 items-center", children: [_jsxs("div", { className: "relative", "data-aos": "zoom-in", children: [_jsx("img", { src: "/assets/img/about.jpg", alt: "Sobre el hospital", className: "rounded-lg shadow-lg w-full" }), _jsx("a", { href: "https://www.youtube.com/watch?v=Y7f98aduVJ8", target: "_blank", rel: "noopener noreferrer", className: "absolute inset-0 flex items-center justify-center group", children: _jsx("div", { className: "bg-[#1977cc] text-white w-16 h-16 rounded-full flex items-center justify-center text-2xl shadow-lg transition-transform transform group-hover:scale-110", children: "\u25B6" }) })] }), _jsxs("div", { "data-aos": "fade-left", children: [_jsx("h2", { className: "text-3xl font-bold text-[#1977cc] mb-4 font-heading", children: "Sobre Nosotros" }), _jsx("p", { className: "text-gray-700 mb-6", children: "En el Hospital Santa B\u00E1rbara nos dedicamos a brindar atenci\u00F3n m\u00E9dica integral y humana. Contamos con personal especializado, infraestructura moderna y un compromiso firme con la salud de nuestra comunidad." }), _jsxs("ul", { className: "space-y-6", children: [_jsxs("li", { className: "flex items-start gap-4", children: [_jsx(FaVial, { className: "text-[#1977cc] text-xl mt-1" }), _jsxs("div", { children: [_jsx("h5", { className: "font-semibold text-gray-800", children: "Laboratorio cl\u00EDnico confiable" }), _jsx("p", { className: "text-gray-600 text-sm", children: "Resultados precisos para diagn\u00F3sticos certeros." })] })] }), _jsxs("li", { className: "flex items-start gap-4", children: [_jsx(FaPumpMedical, { className: "text-[#1977cc] text-xl mt-1" }), _jsxs("div", { children: [_jsx("h5", { className: "font-semibold text-gray-800", children: "Tecnolog\u00EDa de vanguardia" }), _jsx("p", { className: "text-gray-600 text-sm", children: "Equipamiento moderno para una mejor atenci\u00F3n." })] })] }), _jsxs("li", { className: "flex items-start gap-4", children: [_jsx(FaHeart, { className: "text-[#1977cc] text-xl mt-1" }), _jsxs("div", { children: [_jsx("h5", { className: "font-semibold text-gray-800", children: "Atenci\u00F3n humanizada" }), _jsx("p", { className: "text-gray-600 text-sm", children: "Nos enfocamos en el bienestar f\u00EDsico y emocional del paciente." })] })] })] })] })] }) }));
}
